### ISSUE TITLE
FontAwesome not found, Waffle version 0.7.0, R version 3.4.3 (2017-11-30)

### ISSUE THREAD

**Issue by cawoodjm** [hrbrmstr/waffle#42]
_**Version Details**_
R version 3.4.3 (2017-11-30)
Waffle version 0.7.0

**_Issue_**
When I run the below script I receive the following error message.  

"Error: FontAwesome not found. Install via: https://github.com/FortAwesome/Font-Awesome/tree/master/fonts"
*** Please note, when I follow the above link it takes users to a 404 error page. ***

The steps I followed to correct, were to install the Fontawesome files from GitHub as indicated in the waffle package support documentation. I checked that he FA fonts were loaded by running fa_list(), which returned the list of fonts available. I would like to know if I need to call the FA fonts in a different manner to use the use_glyph function within waffle.

_**Script**_
library(waffle)
test <- c(40)
waffle(test, rows=1,use_glyph = 'male')

**Comment by micmart** [comment]
I have the same issue it seems:

> waffle(tmp, rows=8, use_glyph = "child")
Error in readLines(fa_url) : HTTP error 404.

Having a quick glance, it looks like this link in your code @hrbrmstr is invalid:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/css/font-awesome.css

So it seems you are using a css stylesheet from that location which is not valid any more.

BW

**Comment by cawoodjm** [comment]
The example script was a bit busy for this thread, so I simplified it. I do not have control if the package is using CSS style, it loaded that way when the package was installed. What I really desire is to just use a custom glyph to use with the waffle package.

**Comment by silvioaugustojr** [comment]
Hi,
I can use emojifont and font awesome by using the X11() window. However, I can't load font awesome using waffle package.

I have all packages and fonts successfully installed, but I still getting the same error message:

`waffle(c(50, 30, 15, 5), rows = 5, use_glyph = "child", glyph_size = 6, title = "Look I made an infographic using R!")
Error: FontAwesome not found. Install via: https://github.com/FortAwesome/Font-Awesome/tree/master/fonts`

# code
`library(ggplot2)
library(emojifont)
library(waffle)
library(extrafont)

system.file("fonts", package="waffle")

load.fontawesome()

load.fontawesome(font = "fontawesome-webfont.ttf")

X11()

set.seed(2016-03-09)
fa <- fontawesome(c('fa-github', 'fa-weibo', 'fa-twitter', 'fa-android', 'fa-coffee'))
d <- data.frame(x=rnorm(20),
                y=rnorm(20),
                label=sample(fa, 20, replace=T))

ggplot(d, aes(x, y, color=label, label=label)) +
  geom_text(family='fontawesome-webfont', size=6)+
  xlab(NULL)+ylab(NULL) +
  theme(legend.text=element_text(family='fontawesome-webfont'))

ggplot() + geom_fontawesome("fa-github", color='black') + theme_void()

# this is working, it shows a lot of squares.
waffle(c(50, 30, 15, 5), rows = 5, title = "Your basic waffle chart")

# this one shows me the error FontAwesome not found, even though I have succesfully installed all the packages above.
waffle(c(50, 30, 15, 5), rows = 5, use_glyph = "child", glyph_size = 6, 
       title = "Look I made an infographic using R!")`

Does anyone can help me with this?

**Comment by hrbrmstr** [comment]
FontAwesome needs to be installed as a system (i.e. OS) font _and_ made available to R via `extrafont`'s font-import capabilities.

**Comment by silvioaugustojr** [comment]
Ok. I did: 
```
font_import()
fonts()[grep("Awesome", fonts())]
# [1] "FontAwesome"
```

It worked, now I can plot inside rstudio. 

However, I can't see the icons, just weird rectangles:
![erro-waffle](https://user-images.githubusercontent.com/24513810/38811711-a2342a00-4160-11e8-9f4c-1163a0368c46.png)

Then I saw that other people are experiencing the same issue: https://github.com/hrbrmstr/waffle/issues/43

I tried to install both 5.0 and 4.7 (as suggested by other user) versions, however I still getting the rectangles instead of images, even when I call X11() first.

Any ideas how to fix this?

PS. Using macbook it is happening the same thing.

**Comment by silvioaugustojr** [comment]
## In order to help other users experiencing same issue:

After installing _fontawesome.ttf_ and call `font_import()` and `loadfonts(device = "win")` I was finally able to see few icons, however not all of them.

This is how it lookslike when the icon works:
```
waffle(c(50, 30, 15, 5), rows = 5, use_glyph = "music", glyph_size = 6)
```
![music-icon](https://user-images.githubusercontent.com/24513810/38820005-3fed6394-4173-11e8-84c2-06da6a650669.png)

This is how it lookslike when the icon is not available (there is also the weird rectangle as I described above):
```
waffle(c(50, 30, 15, 5), rows = 5, use_glyph = "calculator", glyph_size = 6)
```
![calculator-icon](https://user-images.githubusercontent.com/24513810/38820214-a1529d0c-4173-11e8-9f93-e02a290bf84f.png)

**This is a list with icons that are currently working for me:** medkit, ambulance, bolt, circle, home, phone, music, film, plane, play, comments.

**This is a list with icons that are not working:** bed, calculator, money-bill-alt, percent, bicycle, adress-book, parachute-box, map, newspapper, bus, podcast, exchange-alt, warnings.

**Comment by mcgriffiths** [comment]
I get the boxes with a dot in as posted above regardless of which glyph I try. Did you ever manage to fix this?

**Comment by stonegz** [comment]
1. fontawesome-webfont.ttf is needed rather than the .otf one;
2. install above ttf to the OS font;
3. font_import it with extrafont package, and loadfonts(device = "win") when you are using windows;
4. it will work fine with some icons as @silvioaugustojr listed.

**Comment by soroosj** [comment]
I am running into a similar issue.  I have downloaded the desktop version of Font Awesome.  I see otf files but not ttf files.  How do I find those?

https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started

**Comment by yiqinfu** [comment]
@soroosj If you download the "web" version (https://fontawesome.com/download) you should see the `ttf` files.

**Comment by soroosj** [comment]
Thanks - I have found the ttf files now, deleted the prior OTFs and imported into my Mac fonts. Unfortunately now I get an error message instead of dots when creating a waffle chart.
In R I imported fonts via > font_import()/Users/joelsoroos/Library/Fonts/fa-brands-400.ttf => /Library/Frameworks/R.framework/Versions/3.5/Resources/library/extrafontdb/metrics/fa-brands-400/Users/joelsoroos/Library/Fonts/fa-regular-400.ttf => /Library/Frameworks/R.framework/Versions/3.5/Resources/library/extrafontdb/metrics/fa-regular-400/Users/joelsoroos/Library/Fonts/fa-solid-900.ttf => /Library/Frameworks/R.framework/Versions/3.5/Resources/library/extrafontdb/metrics/fa-solid-900
I ran loadfonts() and seeRegistering font with R using pdfFonts(): Font Awesome 5 Brands RegularRegistering font with R using pdfFonts(): Font Awesome 5 Free RegularRegistering font with R using pdfFonts(): Font Awesome 5 Free Solid
All seems loaded:fonts()[grep("Awesome", fonts())][1] "Font Awesome 5 Brands Regular" "Font Awesome 5 Free Regular"   "Font Awesome 5 Free Solid"    
However, when I run below code, instead of dots with the otf files, I get this message: Error: FontAwesome not found. Install via: https://github.com/FortAwesome/Font-Awesome/tree/master/fonts
parts <- c(80, 30, 20, 10)waffle(parts, rows = 8, use_glyph = "circle", glyph_size =8)


Joel 

    On Sunday, February 17, 2019, 4:56:18 PM CST, yiqinfu <notifications@github.com> wrote:  
 
 
@soroosj If you download the "web" version (https://fontawesome.com/download) you should see the ttf files.

**Comment by acircled** [comment]
I have the same issue. I have installed the .ttfs. When I use font_import(), Font Awesome never shows up in the list.  I have tried V 4 and V5.

**Comment by kristadatasci** [comment]
Still, Font Awesome doesn't show up on the list.

**Comment by Sumidu** [comment]
Same error as apsteinmetz but on a mac

`fonttable() %>% filter(str_detect(FamilyName,"^Font.")) %>% select(fontfile,FamilyName)`

yields

      fontfile              FamilyName 
   1 /Users/andrecalerovaldez/Library/Fonts/fa-brands-400.ttf Font Awesome 5 Brands Regular
   2  /Users/andrecalerovaldez/Library/Fonts/fa-solid-900.ttf     Font Awesome 5 Free Solid

Then calls to waffle create this warning
`In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "FontAwesome5Free-Solid"`

:(

**Comment by amazzarolo** [comment]
Has there ever been anymore solutions to this? Still experiencing this issue. I have downloaded everything properly with `fonts()[grep("Awesome", fonts())]` displaying "FontAwesome", yet when I go to plot a waffle chart with the music glyph I receive this error message: `font family 'FontAwesome' not found, will use 'wqy-microhei' instead`. Any help is appreciated!

**Comment by eirini-zormpa** [comment]
having the same problem as @amazzarolo

**Comment by fronori** [comment]
I experienced the same probllem as @eirini-zormpa and @amazzarolo.
But the following walkthrough solved the issue in my macOS environment:

First, check the font names and its file location:
```
fonttable() %>% 
  dplyr::filter(stringr::str_detect(FamilyName,"^Font.")) %>% 
  select(FontName, fontfile)
```
    FontName                                       fontfile
1. FontAwesome5Brands-Regular  /Users/fronori/Library/Fonts/fa-brands-400.ttf
2. FontAwesome5Free-Regular /Users/fronori/Library/Fonts/fa-regular-400.ttf
3. FontAwesome5Free-Solid   /Users/fronori/Library/Fonts/fa-solid-900.ttf

If any FontAwesome font is not appeared, install the proper .ttf files into your OS first.

Second, add Awesome fonts and its file locations to R by the font_add() function of showtext package. You can specify the FontName and fontfile displayed in the above step. Then, showtext_auto() function allows newly opened graphics devices to use the showtext to draw text.
```
library(showtext)
font_add(family = "FontAwesome5Free-Solid", regular = "/Users/fronori/Library/Fonts/fa-solid-900.ttf")
font_add(family = "FontAwesome5Free-Regular", regular = "/Users/fronori/Library/Fonts/fa-regular-400.ttf")
font_add(family = "FontAwesome5Brands-Regular", regular = "/Users/fronori/Library/Fonts/fa-brands-400.ttf")
showtext_auto()
```

Finaly, voila!
`waffle(c(50, 30, 15, 5), rows = 5, use_glyph = "music", glyph_size = 6)
`
In may case, Roboto Condensed is also needed to use waffle package without warnings. So I installed it.
I hope this post will be helpful for those who suffer from similar problems!

`sessionInfo()`
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

**Comment by ccb2n19** [comment]
After a while of frustration, following the clear instructions here did it for me eventually:

https://www.listendata.com/2019/06/create-infographics-with-r.html
